server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: file:///Users/jihwanlim/Workspace/netflix-clone/configs
          default-label: main
